language: objective-c
osx_image: xcode7.2
script:
- xcodebuild -project Tests/RDHDecimalNumberOperations.xcodeproj -scheme RDHDecimalNumberOperations clean build test
- xcodebuild -project Tests/RDHDecimalNumberOperations.xcodeproj -scheme RDHDecimalNumberOperations  -destination "platform=iOS Simulator,name=iPhone 6" clean build test
- xcodebuild -project Tests/RDHDecimalNumberOperations.xcodeproj -scheme RDHDecimalNumberOperations  -destination "platform=tvOS Simulator,name=Apple TV 1080p" clean build test